apiVersion: v1
kind: Service
metadata:
  name: imaginary
spec:
  type: ClusterIP
  ports:
  - port: 9000
  selector:
    app: imaginary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imaginary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imaginary
  template:
    metadata:
      labels:
        app: imaginary
    spec:
      containers:
      - name: imaginary
        image: ghcr.io/razzie/imaginary:1.2.4
        args:
        - -enable-url-source
        ports:
        - containerPort: 9000
