apiVersion: v1
kind: Service
metadata:
  name: imaginary
spec:
  type: ClusterIP
  ports:
  - port: 9000
  selector:
    app: imaginary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imaginary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imaginary
  template:
    metadata:
      labels:
        app: imaginary
    spec:
      containers:
      - name: imaginary
        image: ghcr.io/razzie/imaginary:35c87ba
        args:
        - -p
        - "9000"
        - -enable-url-source
        - -return-size
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "256Mi"
            cpu: "500m"
