{{ if .Values.telegram.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: telegram-apiserv
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: telegram-apiserv
---
apiVersion: v1
kind: Secret
metadata:
  name: telegram-apiserv-secret
type: Opaque
data:
  apiID: {{ .Values.telegram.apiID | b64enc | quote }}
  apiHash: {{ .Values.telegram.apiHash | b64enc | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-apiserv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-apiserv
  template:
    metadata:
      labels:
        app: telegram-apiserv
    spec:
      containers:
      - name: telegram-apiserv
        image: ghcr.io/razzie/telegram-apiserv:latest
        args:
        - --api-id=$(API_ID)
        - --api-hash=$(API_HASH)
        - --http-port=8080
        - --local
        ports:
        - containerPort: 8080
        env:
        - name: API_ID
          valueFrom:
            secretKeyRef:
              name: telegram-apiserv-secret
              key: apiID
        - name: API_HASH
          valueFrom:
            secretKeyRef:
              name: telegram-apiserv-secret
              key: apiHash
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: {{ .Values.telegram.memoryLimit | quote }}
            cpu: {{ .Values.telegram.cpuLimit | quote }}
{{ end }}
