helmDefaults:
  createNamespace: true
  historyMax: 2
  disableValidation: true

helmfiles:
- ./shared/helmfile.yaml
- ./apps/helmfile.yaml
- ./mailserver/helmfile.yaml
- ./nextcloud/helmfile.yaml
- ./irc/helmfile.yaml
