repositories:
- name: razzie
  url: https://razzie.github.io/helm-charts
- name: traefik
  url: https://helm.traefik.io/traefik
- name: jetstack
  url: https://charts.jetstack.io
- name: emberstack
  url: https://emberstack.github.io/helm-charts

helmDefaults:
  createNamespace: true
  historyMax: 2

releases:
- name: raz-stack-shared
  namespace: shared
  chart: ./shared/
  needs:
  - traefik/traefik
  - cert-manager/cert-manager
  - cert-manager/cert-manager-webhook-namecheap
  - shared/k8s-db-operator
  values:
  - ./shared/values.yaml
  - namecheap:
      apiKey: {{ requiredEnv "NAMECHEAP_API_KEY" | quote }}
      apiUser: {{ requiredEnv "NAMECHEAP_API_USER" | quote }}

- name: raz-stack-apps
  namespace: apps
  chart: ./apps/
  needs:
  - shared/raz-stack-shared
  values:
  - publicBucketUrl: {{ requiredEnv "PUBLIC_BUCKET_URL" | quote }}
  - pizzabotToken: {{ requiredEnv "PIZZABOT_TOKEN" | quote }}

- name: traefik
  namespace: traefik
  chart: traefik/traefik
  values:
  - service:
      annotationsTCP:
        service.beta.kubernetes.io/linode-loadbalancer-default-proxy-protocol: "v2"
        service.beta.kubernetes.io/scw-loadbalancer-proxy-protocol-v2: "true"
        service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  - additionalArguments:
    - --entrypoints.web.http.redirections.entryPoint.to=:443
    - --entrypoints.web.http.redirections.entryPoint.scheme=https
    - --entrypoints.web.http.redirections.entrypoint.permanent=true
    - --entryPoints.web.proxyProtocol.insecure=true
    - --entryPoints.web.forwardedHeaders.insecure=true
    - --entryPoints.websecure.proxyProtocol.insecure=true
    - --entryPoints.websecure.forwardedHeaders.insecure=true

- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  values:
  - installCRDs: true

- name: cert-manager-webhook-namecheap
  namespace: cert-manager
  chart: razzie/cert-manager-webhook-namecheap
  needs:
  - cert-manager/cert-manager

- name: reflector
  namespace: reflector
  chart: emberstack/reflector

- name: k8s-db-operator
  namespace: shared
  chart: razzie/k8s-db-operator
  values:
  - ./shared/values.yaml
