{{ $domains := list }}
{{ range .Values.email.accounts }}
{{ $domains = append $domains (split "@" .account)._1 }}
{{ end }}
{{ $domains = uniq $domains }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mailserver-cert
spec:
  secretName: mailserver-cert
  commonName: mail.gorzsony.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  dnsNames:
  - "mail.gorzsony.com"
{{ range $domains }}
  - {{ . | quote }}
{{ end }}
