apiVersion: v1
kind: Secret
metadata:
 name: mirror-gorzsony-com-cert
 annotations:
   reflector.v1.k8s.emberstack.com/reflects: "shared/gorzsony-com-cert"
   reflector.v1.k8s.emberstack.com/reflected-version: ""
