apiVersion: v1
kind: ConfigMap
metadata:
  name: mailserver-config
data:
  postfix-main.cf: |
    postscreen_upstream_proxy_protocol = haproxy
    {{- if .Values.email.relay.enabled }}
    relayhost = [{{ .Values.email.relay.host }}]:{{ .Values.email.relay.port }}
    smtp_use_tls = yes
    smtp_tls_security_level = encrypt
    smtp_sasl_auth_enable = yes
    smtp_sasl_password_maps = hash:/tmp/docker-mailserver/sasl_passwd
    smtp_sasl_security_options = noanonymous
    smtp_sasl_tls_security_options = noanonymous
    {{- end }}
    mydestination = localhost.$mydomain, localhost
  postfix-master.cf: |
    submission/inet/smtpd_upstream_proxy_protocol=haproxy
    smtp/inet/smtpd_upstream_proxy_protocol=haproxy
    smtps/inet/smtpd_upstream_proxy_protocol=haproxy
  dovecot.cf: |
    {{- with (first (lookup "v1" "Service" "traefik" "traefik").status.loadBalancer.ingress) }}
    haproxy_trusted_networks = 127.0.0.1/32,10.0.0.0/8,100.64.0.0/10,{{ .ip }}/32
    haproxy_timeout = 3 secs
    {{- end }}
    service imap-login {
      inet_listener imaps {
        haproxy = yes
        ssl = yes
        port = 10993
      }
    }
    service pop3-login {
      inet_listener pop3s {
        haproxy = yes
        ssl = yes
        port = 10995
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: mailserver-secret
type: Opaque
stringData:
  postfix-accounts.cf: |-
    {{- range .Values.email.accounts }}
    {{ .account }}|{BLF-CRYPT}{{ bcrypt .password }}
    {{- end }}
  {{- if .Values.email.relay.enabled }}
  sasl_passwd: |-
    [{{ .Values.email.relay.host }}]:{{ .Values.email.relay.port }}  {{ .Values.email.relay.username }}:{{ .Values.email.relay.password }}
  {{- end }}
