apiVersion: v1
kind: Service
metadata:
  name: mailserver
spec:
  type: ClusterIP
  ports:
  - port: 25
    name: smtp
  - port: 465
    name: smtp-tls
  - port: 993
    targetPort: 10993
    name: imap-tls
  - port: 995
    targetPort: 10995
    name: pop3-tls
  selector:
    app: mailserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: mailserver
    spec:
      containers:
      - name: mailserver
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - >
                  mkdir -p /tmp/docker-mailserver;
                  cp /mailserver-config/* /tmp/docker-mailserver/;
                  {{- if .Values.email.relay.enabled }}
                  postmap hash:/tmp/docker-mailserver/sasl_passwd;
                  {{- end }}
        ports:
        - containerPort: 25
        - containerPort: 465
        - containerPort: 10993
        - containerPort: 10995
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: OVERRIDE_HOSTNAME
          value: raz-stack.tld
        - name: ONE_DIR
          value: "1"
        - name: TLS_LEVEL
          value: modern
        - name: SSL_TYPE
          value: manual
        - name: SSL_CERT_PATH
          value: /var/mail-certs/tls.crt
        - name: SSL_KEY_PATH
          value: /var/mail-certs/tls.key
        - name: ENABLE_POP3
          value: "1"
        volumeMounts:
        - mountPath: "/var/mail"
          subPath: mail
          name: storage-vol
        - mountPath: "/var/mail-state"
          subPath: mail-state
          name: storage-vol
        - mountPath: "/var/log/mail"
          subPath: log
          name: storage-vol
        - mountPath: "/mailserver-config"
          name: config-vol
        - mountPath: "/var/mail-certs"
          name: cert-vol
      volumes:
      - name: storage-vol
        persistentVolumeClaim:
          claimName: mailserver-pvc
      - name: config-vol
        projected:
          sources:
          - configMap:
              name: mailserver-config
          - secret:
              name: mailserver-secret
      - name: cert-vol
        secret:
          secretName: mailserver-cert
