apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gorzsony-com-cert
spec:
  secretName: gorzsony-com-cert
  commonName: gorzsony.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  dnsNames:
  - "gorzsony.com"
  - "*.gorzsony.com"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: razzie-xyz-cert
spec:
  secretName: razzie-xyz-cert
  commonName: razzie.xyz
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  dnsNames:
  - "razzie.xyz"
  - "*.razzie.xyz"
