apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mediaserver-route
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`mediaserver.gorzsony.com`)
    kind: Rule
    services:
    - name: mediaserver
      port: 8080
  tls:
    secretName: mirror-gorzsony-com-cert
---
apiVersion: k8s-db-operator.razzie.github.io/v1alpha1
kind: DatabaseClaim
metadata:
  name: mediaserver-dbclaim
spec:
  databaseType: Redis
  secretName: mediaserver-redis-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mediaserver
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: mediaserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediaserver
  template:
    metadata:
      labels:
        app: mediaserver
    spec:
      containers:
      - name: mediaserver
        image: ghcr.io/razzie/mediaserver:v1.4
        args:
        - -redis
        - $(REDIS_ADDR)
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_ADDR
          valueFrom:
            secretKeyRef:
              name: mediaserver-redis-secret
              key: connectionString
        resources:
          requests:
            memory: "8Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "100m"
