{{ if .Values.pizzabotToken }}
apiVersion: v1
kind: Secret
metadata:
  name: pizzabot-secret
type: Opaque
data:
  token: {{ .Values.pizzabotToken | b64enc | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzabot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizzabot
  template:
    metadata:
      labels:
        app: pizzabot
    spec:
      containers:
      - name: pizzabot
        image: ghcr.io/razzie/pizzabot:v1.0
        env:
        - name: PIZZABOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: pizzabot-secret
              key: token
        resources:
          requests:
            memory: "8Mi"
            cpu: "25m"
          limits:
            memory: "16Mi"
            cpu: "100m"
{{ end }}
