{{ if .Values.pizzabot.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pizzabot-secret
type: Opaque
data:
  PIZZABOT_TOKEN: {{ .Values.pizzabot.token | b64enc | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzabot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizzabot
  template:
    metadata:
      labels:
        app: pizzabot
    spec:
      containers:
      - name: pizzabot
        image: ghcr.io/razzie/pizzabot:v1.0
        args:
        - $(PIZZABOT_TOKEN)
        envFrom:
        - secretRef:
            name: pizzabot-secret
        resources:
          requests:
            memory: "8Mi"
            cpu: "25m"
          limits:
            memory: "16Mi"
            cpu: "100m"
{{ end }}
