apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: razchess-route
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`chess.razzie.xyz`)
    kind: Rule
    services:
    - name: razchess
      port: 8080
  tls:
    secretName: mirror-razzie-xyz-cert
---
apiVersion: k8s-db-operator.razzie.github.io/v1alpha1
kind: DatabaseClaim
metadata:
  name: razchess-dbclaim
spec:
  databaseType: Redis
  secretName: razchess-redis-secret
---
apiVersion: v1
kind: Service
metadata:
  name: razchess
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: razchess
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: razchess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: razchess
  template:
    metadata:
      labels:
        app: razchess
    spec:
      containers:
      - name: razchess
        image: ghcr.io/razzie/razchess:v1.1
        args:
        - -redis
        - $(REDIS_ADDR)
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_ADDR
          valueFrom:
            secretKeyRef:
              name: razchess-redis-secret
              key: connectionString
        resources:
          requests:
            memory: "8Mi"
            cpu: "25m"
          limits:
            memory: "32Mi"
            cpu: "100m"
