apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: razlink-route
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`link.gorzsony.com`)
    kind: Rule
    services:
    - name: razlink
      port: 8080
  tls:
    secretName: mirror-gorzsony-com-cert
---
apiVersion: k8s-db-operator.razzie.github.io/v1alpha1
kind: DatabaseClaim
metadata:
  name: razlink-dbclaim
spec:
  databaseType: Redis
  secretName: razlink-redis-secret
---
apiVersion: v1
kind: Service
metadata:
  name: razlink
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: razlink
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: razlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: razlink
  template:
    metadata:
      labels:
        app: razlink
    spec:
      containers:
      - name: razlink
        image: ghcr.io/razzie/razlink:v2.3
        args:
        - -redis
        - $(REDIS_ADDR)
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_ADDR
          valueFrom:
            secretKeyRef:
              name: razlink-redis-secret
              key: connectionString
        resources:
          requests:
            memory: "8Mi"
            cpu: "25m"
          limits:
            memory: "32Mi"
            cpu: "100m"
