apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: raztalk-route
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`talk.gorzsony.com`)
    kind: Rule
    services:
    - name: raztalk
      port: 8080
  tls:
    secretName: gorzsony-com-cert
---
apiVersion: v1
kind: Service
metadata:
  name: raztalk
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: raztalk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raztalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raztalk
  template:
    metadata:
      labels:
        app: raztalk
    spec:
      containers:
      - name: raztalk
        image: ghcr.io/razzie/raztalk:v1.1
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "500m"
