apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: website-route-1
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`gorzsony.com`)
    kind: Rule
    services:
    - name: website
      port: 8080
  tls:
    secretName: gorzsony-com-cert
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: website-route-2
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`razzie.xyz`)
    kind: Rule
    services:
    - name: website
      port: 8080
  tls:
    secretName: razzie-xyz-cert
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: ghcr.io/razzie/personal-website:v2.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "8Mi"
            cpu: "25m"
          limits:
            memory: "32Mi"
            cpu: "100m"
