repositories:
- name: razzie
  url: https://razzie.github.io/helm-charts

releases:
- name: nextcloud-deps
  namespace: nextcloud
  chart: .
  values:
  - ./values.yaml.gotmpl

- name: nextcloud
  namespace: nextcloud
  chart: razzie/nextcloud
  needs:
  - nextcloud/nextcloud-deps
  values:
  - ./values.yaml.gotmpl
