#image:
#  flavor: fpm

nextcloud:
  host: nextcloud.razzie.xyz
  username: razzie
  password: password

  s3:
    bucket: #NEXTCLOUD_S3_BUCKET
    endpoint: #NEXTCLOUD_S3_ENDPOINT
    region: #NEXTCLOUD_S3_REGION
    accessKey: #NEXTCLOUD_S3_ACCESS_KEY
    secretKey: #NEXTCLOUD_S3_SECRET_KEY

  backupPassword: #NEXTCLOUD_BACKUP_PASSWORD

  configs:
    custom.config.php: |-
      <?php
      $CONFIG = array (
        'overwriteprotocol' => 'https',
        'overwrite.cli.url' => 'https://nextcloud.razzie.xyz',
        'filelocking.enabled' => 'true',
        'loglevel' => '2',
        'enable_previews' => true,
        'trusted_domains' =>
           [
            'nextcloud.razzie.xyz'
           ],
        'directory' => getenv('NEXTCLOUD_DATA_DIR') ?: '/var/www/html/data'
      );
    postgres.config.php: |-
      <?php
      $postgresConnStr = parse_url(getenv('POSTGRES_ADDR'));
      $CONFIG = array (
        'dbtype' => 'pgsql',
        'dbname' => substr($postgresConnStr['path'], 1),
        'dbuser' => $postgresConnStr['user'],
        'dbpassword' => urldecode($postgresConnStr['pass']),
        'dbhost' => $postgresConnStr['host'],
        'dbport' => $postgresConnStr['port'] ?? 5432
      );
    redis.config.php: |-
      <?php
      $redisConnStr = parse_url(getenv('REDIS_ADDR'));
      $CONFIG = array (
        'memcache.local' => '\\OC\\Memcache\\Redis',
        'memcache.distributed' => '\OC\Memcache\Redis',
        'memcache.locking' => '\OC\Memcache\Redis',
        'redis' => array(
          'host' => $redisConnStr['host'],
          'port' => $redisConnStr['port'],
          'password' => urldecode($redisConnStr['pass'])
        )
      );
    s3.config.php: |-
      <?php
      $CONFIG = array (
        'objectstore' => array(
          'class' => '\\OC\\Files\\ObjectStore\\S3',
          'arguments' => array(
            'bucket'     => getenv('S3_BUCKET'),
            'autocreate' => false,
            'key'        => getenv('S3_ACCESS_KEY'),
            'secret'     => getenv('S3_SECRET_KEY'),
            'region'     => getenv('S3_REGION'),
            'hostname'   => getenv('S3_ENDPOINT'),
            'use_ssl'    => true,
            'use_path_style' => true
          )
        )
      );

  defaultConfigs:
    .htaccess: true
    apache-pretty-urls.config.php: true
    apcu.config.php: true
    apps.config.php: true
    autoconfig.php: false
    redis.config.php: false
    smtp.config.php: true

  extraEnv:
  - name: POSTGRES_ADDR
    valueFrom:
      secretKeyRef:
        name: nextcloud-postgres-secret
        key: connectionString
  - name: REDIS_ADDR
    valueFrom:
      secretKeyRef:
        name: nextcloud-redis-secret
        key: connectionString
  - name: S3_BUCKET
    valueFrom:
      secretKeyRef:
        name: nextcloud-s3-secret
        key: bucket
  - name: S3_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: nextcloud-s3-secret
        key: endpoint
  - name: S3_REGION
    valueFrom:
      secretKeyRef:
        name: nextcloud-s3-secret
        key: region
  - name: S3_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: nextcloud-s3-secret
        key: accessKey
  - name: S3_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: nextcloud-s3-secret
        key: secretKey

cronjob:
  enabled: false
  image:
    repository: curlimages/curl
    tag: latest
  annotations: {}
  curlInsecure: false
  failedJobsHistoryLimit: 5
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 2

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql

persistence:
  accessMode: ReadWriteOnce
  annotations: {}
  enabled: true
  size: 2Gi

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
startupProbe:
  enabled: false
