apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: irc-tls-route
spec:
  entryPoints:
  - irc-tls
  routes:
  - match: HostSNI(`*`)
    services:
    - name: ircd
      port: 6667
      proxyProtocol:
        version: 2
  tls:
    secretName: mirror-razzie-xyz-cert
