apiVersion: v1
kind: ConfigMap
metadata:
  name: ircd-config
data:
  ircd.conf: |
    <server
            name="irc.razzie.xyz"
            description="RazzieIRC"
            network="RazzieIRC">
    
    <admin
           name="Gábor Görzsöny"
           nick="razzie"
           email="gabor@gorzsony.com">
    
    <module
            name="haproxy">

    <bind
          address=""
          port="6667"
          type="clients"
          hook="haproxy">
    
    <connect
             name="main"
             allow="*"
             maxchans="20"
             timeout="20"
             pingfreq="2m"
             hardsendq="1M"
             softsendq="10240"
             recvq="10K"
             threshold="10"
             commandrate="1000"
             fakelag="yes"
             localmax="3"
             globalmax="3"
             resolvehostnames="yes"
             useident="no"
             limit="5000"
             modes="+x">
    
    <cidr
          ipv4clone="32"
          ipv6clone="128">
    
    <class name="SACommands" commands="SAJOIN SAPART SANICK SAQUIT SATOPIC SAKICK SAMODE OJOIN">
    <class name="BanControl" commands="KILL GLINE KLINE ZLINE QLINE ELINE TLINE RLINE CHECK NICKLOCK NICKUNLOCK SHUN CLONES CBAN" usermodes="*" chanmodes="*" snomasks="Xx">
    <class name="OperChat" commands="WALLOPS GLOBOPS" usermodes="*" chanmodes="*" privs="users/mass-message" snomasks="Gg">

    <type
        name="NetAdmin"
        classes="SACommands OperChat BanControl"
        vhost="netadmin.irc.razzie.xyz"
        maxchans="60"
        modes="+s +cCqQ">
    
    <oper name="{{ .Values.ircd.admin.name }}"
          password="{{ bcrypt .Values.ircd.admin.password }}"
          hash="bcrypt"
          class="ServerOperators"
          host="*@irc.razzie.xyz"
          type="NetAdmin"
          vhost="staff.irc.razzie.xyz">
    
    <dns
         timeout="5">
    
    <maxlist
             chan="*"
             limit="100">
    
    <options
             prefixquit="Quit: "
             suffixquit=""
             prefixpart="&quot;"
             suffixpart="&quot;"
             syntaxhints="yes"
             casemapping="ascii"
             cyclehostsfromuser="no"
             announcets="yes"
             allowmismatch="no"
             defaultbind="auto"
             hostintopic="yes"
             pingwarning="15"
             serverpingfreq="1m"
             splitwhois="no"
             defaultmodes="not"
             xlinemessage="You're banned!"
             allowzerolimit="no"
             modesinlist="no"
             exemptchanops="censor:o filter:o nickflood:o nonick:v regmoderated:o"
             invitebypassmodes="yes"
             nosnoticestack="no">
    
    <performance
                 netbuffersize="10240"
                 somaxconn="128"
                 softlimit="12800"
                 clonesonconnect="yes"
                 timeskipwarn="2s"
                 quietbursts="yes">
    
    <security
              allowcoreunload="no"
              announceinvites="dynamic"
              hideulines="no"
              flatlinks="no"
              hidebans="no"
              hidekills=""
              hideulinekills="yes"
              hidesplits="no"
              maxtargets="20"
              customversion=""
              restrictbannedusers="yes"
              genericoper="no"
              userstats="Pu">
    
    <limits
            maxaway="200"
            maxchan="60"
            maxhost="64"
            maxident="12"
            maxkick="300"
            maxmodes="20"
            maxnick="30"
            maxquit="300"
            maxreal="130"
            maxtopic="330">
    
    <log
         method="file"
         type="* -USERINPUT -USEROUTPUT"
         level="default"
         target="/dev/stdout">
    
    <whowas
            groupsize="10"
            maxgroups="100000"
            maxkeep="3d">
