apiVersion: v1
kind: Service
metadata:
  name: ircd
spec:
  type: ClusterIP
  ports:
  - port: 6667
  selector:
    app: ircd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ircd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ircd
  template:
    metadata:
      labels:
        app: ircd
    spec:
      securityContext:
        fsGroup: 10000
      containers:
      - name: ircd
        image: {{ .Values.ircd.image.repository }}:{{ .Values.ircd.image.tag }}
        ports:
        - containerPort: 6667
        volumeMounts:
        - mountPath: "/inspircd/conf/inspircd.conf"
          subPath: ircd.conf
          name: config-vol
        - mountPath: "/inspircd/data"
          name: data-vol
      volumes:
      - name: config-vol
        configMap:
          name: ircd-config
      - name: data-vol
        persistentVolumeClaim:
          claimName: ircd-pvc
