apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-backup-secret
type: Opaque
data:
  password: {{ .Values.nextcloud.backupPassword | b64enc | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-backup-s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-backup-s3
  template:
    metadata:
      labels:
        app: postgres-backup-s3
    spec:
      containers:
      - name: postgres-backup-s3
        image: razzquez/postgres-backup-s3:latest
        env:
        - name: SCHEDULE
          value: "@daily"
        - name: BACKUP_KEEP_DAYS
          value: "14"
        - name: PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: nextcloud-backup-secret
              key: password
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
                name: nextcloud-postgres-secret
                key: connectionString
        - name: POSTGRES_DATABASE
          value: nextcloud # just for naming the dump files
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
                name: nextcloud-s3-secret
                key: bucket
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
                name: nextcloud-s3-secret
                key: endpoint
        - name: S3_REGION
          valueFrom:
            secretKeyRef:
                name: nextcloud-s3-secret
                key: region
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
                name: nextcloud-s3-secret
                key: accessKey
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
                name: nextcloud-s3-secret
                key: secretKey
        resources:
          requests:
            memory: "8Mi"
            cpu: "100m"
          limits:
            memory: "32Mi"
            cpu: "100m"
