apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: razzie-cloud-cert
spec:
  secretName: razzie-cloud-cert
  commonName: razzie.cloud
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  dnsNames:
  - "razzie.cloud"
