apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-s3-secret
type: Opaque
data:
  bucket: {{ .Values.nextcloud.s3.bucket | b64enc | quote }}
  endpoint: {{ .Values.nextcloud.s3.endpoint | b64enc | quote }}
  region: {{ .Values.nextcloud.s3.region | b64enc | quote }}
  accessKey: {{ .Values.nextcloud.s3.accessKey | b64enc | quote }}
  secretKey: {{ .Values.nextcloud.s3.secretKey | b64enc | quote }}
  encryptionKey: {{ .Values.nextcloud.s3.encryptionKey | b64enc | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: s3proxy
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: s3proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3proxy
  template:
    metadata:
      labels:
        app: s3proxy
    spec:
      containers:
      - name: s3proxy
        image: ghcr.io/razzie/s3proxy:v1.0
        args:
        - -endpoint
        - https://$(S3_ENDPOINT)
        - -encryption-key
        - $(S3_ENCRYPTION_KEY)
        ports:
        - containerPort: 8080
        env:
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: nextcloud-s3-secret
              key: endpoint
        - name: S3_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: nextcloud-s3-secret
              key: encryptionKey
        resources:
          requests:
            memory: "8Mi"
            cpu: "25m"
          limits:
            memory: "256Mi"
            cpu: "200m"
