repositories:
- name: razzie
  url: https://razzie.github.io/helm-charts

releases:
- name: raz-stack-shared
  namespace: shared
  chart: .
  needs:
  - traefik/traefik
  - cert-manager/cert-manager
  - cert-manager/cert-manager-webhook-namecheap
  - shared/k8s-db-operator
  values:
  - ./values.yaml.gotmpl

- name: traefik
  namespace: traefik
  chart: razzie/traefik
  values:
  - ./config/traefik-config.yaml.gotmpl

- name: cert-manager
  namespace: cert-manager
  chart: razzie/cert-manager
  values:
  - ./config/cert-manager-config.yaml

- name: cert-manager-webhook-namecheap
  namespace: cert-manager
  chart: razzie/cert-manager-webhook-namecheap
  needs:
  - cert-manager/cert-manager
  values:
  - ./config/cert-manager-webhook-namecheap-config.yaml

- name: k8s-db-operator
  namespace: shared
  chart: razzie/k8s-db-operator
  values:
  - ./values.yaml.gotmpl
  - version: v1.0
